name: Manual .NET Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”” Start build process
        run: echo "Build process has started..."

      - &echo-template
        name: ğŸ”” Echo template
        run: echo "This is a reusable echo step."
        shell: bash # will persist unless explicitly overridden

      - name: ğŸ“ Show runtime context
        run: |
          echo "ğŸ”§ Runner OS: ${{ runner.os}}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸ“‚ Workflow: ${{ github.workflow }}"
          echo "ğŸš€ Triggered by: ${{ github.event_name }}"
          echo "ğŸ‘¤ Actor: ${{ github.actor }}"
          echo "ğŸ”¢ Run number: ${{ github.run_number }}"
          echo "ğŸŒ¿ Branch: ${{ github.ref }}"
          
      - *echo-template

      - name: ğŸ“¥ Checkout code # downloads the repository's code into the runner's workspace
        uses: actions/checkout@v5

      - name: ğŸ› ï¸ Install .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ—ï¸ Build project
        run: dotnet build

      - name: ğŸƒğŸ¼â€â™€ï¸â€â¡ï¸ Run code
        run: dotnet run --project CleanCodeDevops.App/CleanCodeDevops.App.csproj
